service: blog-craftsmen
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  environment:
    SQS_OFFLINE_ENDPOINT: ${self:custom.serverless-offline-sqs.endpoint}

functions:
  hello:
    handler: ./src/lambda/handler.handle
    events:
      - httpApi:
          path: /
          method: get

custom:
  serverless-offline:
    httpPort: 8080
  esbuild:
    minify: false
    sourcemap: linked
    watch:
      pattern: ['src/**/*.ts']
      ignore: ['node_modules/**/*']
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: ${self:provider.region}
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

plugins:
  - serverless-esbuild
  # Run elasticMQ server `npm run start-elastic-mq` before enabling serverless-offline-sqs.
  - serverless-offline-sqs
  - serverless-offline
